#pragma once

//REG寄存器地址定义
//万兆网卡设备本身相关的配置寄存器
#define  ADDR_VERSION						0x000  //ADDR_DEV_ID
#define  ADDR_CAPABILITY					0x001  //ADDR_DEVICE_CAPABILITY
#define  ADDR_IRQ_EN						0x002  //未变更
#define  ADDR_IRQ							0x003  //未变更
#define  ADDR_OPT_STATUS					0x004
#define  ADDR_MODE_SUPPORT					0x006 // 模式支持
#define  ADDR_PHY_SOFT_RST 					0x03e // 2020/9/7 新定义，此时FPGA固件还没做支持，先规划
#define  ADDR_MAC_SOFT_RST					0x03f
#define  ADDR_DNA_H							0x088
#define  ADDR_DNA_L							0x089

/* frame ctrl */
#define ADDR_SNAP_CTRL              0x0040
#define ADDR_FRAME_CTRL             0x0041
#define ADDR_CHK_H                  0x0042
#define ADDR_CHK_V                  0x0043
#define ADDR_ORG_H_SIZE             0x0044
#define ADDR_ORG_V_SIZE             0x0045
#define ADDR_SNAP_DELAY             0x0046
#define ADDR_ROI_H                  0x0047
#define ADDR_ROI_V                  0x0048
#define ADDR_FRAME_ID               0x004d

#define ADDR_STREAM_CTRL            0x0050
#define ADDR_PIX_FORMAT             0x0051  
#define ADDR_DROP_CASE              0x0052
#define ADDR_BUFED_SIZE             0x0053

#define ADDR_PACK_SIZE              0x0054
#define ADDR_PACK_NUM               0x0055


#define ADDR_FRAME_CNT              0x0060
#define ADDR_FRAME_DROP_CNT         0x0061
#define ADDR_NO_START_CNT           0x0062
#define ADDR_NO_END_CNT             0x0063
#define ADDR_BUF_INFIFO_ERR_CNT     0x0064
#define ADDR_BUF_HDR_ERR_CNT        0x0065 
#define ADDR_BUF_ID_ERR_CNT         0x0066
#define ADDR_BUF_CHKSUM_ERR_CNT     0x0067

#define ADDR_NO_FRAME_START_CNT     0x0068
#define ADDR_NO_FRAME_END_CNT       0x0069
#define ADDR_NO_LINE_START_CNT      0x006A
#define ADDR_NO_LINE_END_CNT        0x006B
#define ADDR_H_CHANGED_CNT          0x006C
#define ADDR_V_CHANGED_CNT          0x006D


#define ADDR_LOCAL_I2C_ADPT_CTRL			0x090
#define ADDR_LOCAL_I2C_ADPT_STA				0x091
#define ADDR_LOCAL_I2C_ADPT_CURR			0x092
#define ADDR_LOCAL_I2C_ADPT_TXFF_STA		0x093
#define ADDR_LOCAL_I2C_ADPT_TXFF_WR			0x094
#define ADDR_LOCAL_I2C_ADPT_RXFF_STA		0x095
#define ADDR_LOCAL_I2C_ADPT_RXFF_RD			0x096
#define ADDR_LOCAL_I2C_ADPT_RXFF_RDAT		0x09C

#define ADDR_LOCAL_I2C_CTRL					0x097
#define ADDR_LOCAL_I2C_STA					0x098
#define ADDR_LOCAL_I2C_CLK					0x099
#define ADDR_LOCAL_I2C_WAIT					0x09A

#define ADDR_EEPROM_WP						0x09D



//PCIE卡设备MAC部分的配置寄存器
#define		MAC_OFFSET						0x100
//######################################################
//    寄存器地址定义
//######################################################
#define ADDR_MAC_VERSION                    (MAC_OFFSET+ 0x01)
#define ADDR_MAC_ADDR                       (MAC_OFFSET+ 0x02)
#define ADDR_MAC_IFG                        (MAC_OFFSET+ 0x03)
#define ADDR_MAC_ID_INTERVAL                (MAC_OFFSET+ 0x04)

#define ADDR_ETH0_ADDR_H					(MAC_OFFSET+ 0x10)
#define ADDR_ETH0_ADDR_L					(MAC_OFFSET+ 0x11)
#define ADDR_ETH1_ADDR_H					(MAC_OFFSET+ 0x12)
#define ADDR_ETH1_ADDR_L					(MAC_OFFSET+ 0x13)
#define ADDR_ETH2_ADDR_H					(MAC_OFFSET+ 0x14)
#define ADDR_ETH2_ADDR_L					(MAC_OFFSET+ 0x15)
#define ADDR_ETH3_ADDR_H					(MAC_OFFSET+ 0x16)
#define ADDR_ETH3_ADDR_L					(MAC_OFFSET+ 0x17)

#define ADDR_MAC_ROUTE_CMD               (MAC_OFFSET+ 0x20)
#define ADDR_MAC_ROUTE_DAT0                 (MAC_OFFSET+ 0x21)
#define ADDR_MAC_ROUTE_DAT1                 (MAC_OFFSET+ 0x22)
#define ADDR_MAC_ROUTE_DAT2                 (MAC_OFFSET+ 0x23)
#define ADDR_MAC_ROUTE_DAT3                 (MAC_OFFSET+ 0x24)
															 
#define ADDR_MAC_FLOW_CTRL_HGATE            (MAC_OFFSET+ 0x30)
#define ADDR_MAC_FLOW_CTRL_LGATE            (MAC_OFFSET+ 0x31)
#define ADDR_MAC_RX_CONT_TIMES              (MAC_OFFSET+ 0x32)
#define ADDR_MAC_MATCH_ADDR0                (MAC_OFFSET+ 0x33)
#define ADDR_MAC_MATCH_ADDR1                (MAC_OFFSET+ 0x34)
#define ADDR_MAC_MATCH_ADDR2                (MAC_OFFSET+ 0x35)
#define ADDR_MAC_MATCH_ADDR3                (MAC_OFFSET+ 0x36)
															 
#define ADDR_MAC_RXFF                       (MAC_OFFSET+ 0x40)
#define ADDR_MAC_RX_STA                     (MAC_OFFSET+ 0x41)
#define ADDR_MAC_RX_DAT                     (MAC_OFFSET+ 0x42)
#define ADDR_MAC_TXFF                       (MAC_OFFSET+ 0x48)
#define ADDR_MAC_TX_STA                     (MAC_OFFSET+ 0x49)
#define ADDR_MAC_TX_DAT                     (MAC_OFFSET+ 0x4a)
															 
#define ADDR_MAC_TRANS0_PHY_CNT_RX_UNKNOW   (MAC_OFFSET+ 0x50)
#define ADDR_MAC_TRANS0_PHY_CNT_RX_PACK     (MAC_OFFSET+ 0x51)
#define ADDR_MAC_TRANS0_PHY_CNT_RX_PAUSE    (MAC_OFFSET+ 0x52)
#define ADDR_MAC_TRANS0_PHY_CNT_RX_CRC_ERR  (MAC_OFFSET+ 0x53)
#define ADDR_MAC_TRANS0_PHY_CNT_RX_DROP     (MAC_OFFSET+ 0x54)
#define ADDR_MAC_TRANS0_PHY_CNT_RX_HDR_ERR  (MAC_OFFSET+ 0x55)
#define ADDR_MAC_TRANS0_PHY_CNT_TX_PACK     (MAC_OFFSET+ 0x56)
#define ADDR_MAC_TRANS0_PHY_CNT_TX_PAUSE    (MAC_OFFSET+ 0x57)
#define ADDR_MAC_TRANS0_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0x58)
#define ADDR_MAC_TRANS0_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0x59)
#define ADDR_MAC_TRANS0_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0x5a)
#define ADDR_MAC_TRANS0_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0x5b)
#define ADDR_MAC_TRANS0_BUF_CNT_WR_UNLEGAL  (MAC_OFFSET+ 0x5c)
															 
#define ADDR_MAC_TRANS1_PHY_CNT_RX_UNKNOW   (MAC_OFFSET+ 0x60)
#define ADDR_MAC_TRANS1_PHY_CNT_RX_PACK     (MAC_OFFSET+ 0x61)
#define ADDR_MAC_TRANS1_PHY_CNT_RX_PAUSE    (MAC_OFFSET+ 0x62)
#define ADDR_MAC_TRANS1_PHY_CNT_RX_CRC_ERR  (MAC_OFFSET+ 0x63)
#define ADDR_MAC_TRANS1_PHY_CNT_RX_DROP     (MAC_OFFSET+ 0x64)
#define ADDR_MAC_TRANS1_PHY_CNT_RX_HDR_ERR  (MAC_OFFSET+ 0x65)
#define ADDR_MAC_TRANS1_PHY_CNT_TX_PACK     (MAC_OFFSET+ 0x66)
#define ADDR_MAC_TRANS1_PHY_CNT_TX_PAUSE    (MAC_OFFSET+ 0x67)
#define ADDR_MAC_TRANS1_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0x68)
#define ADDR_MAC_TRANS1_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0x69)
#define ADDR_MAC_TRANS1_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0x6a)
#define ADDR_MAC_TRANS1_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0x6b)
#define ADDR_MAC_TRANS1_BUF_CNT_WR_UNLEGAL  (MAC_OFFSET+ 0x6c)
															 
#define ADDR_MAC_TRANS2_PHY_CNT_RX_UNKNOW   (MAC_OFFSET+ 0x70)
#define ADDR_MAC_TRANS2_PHY_CNT_RX_PACK     (MAC_OFFSET+ 0x71)
#define ADDR_MAC_TRANS2_PHY_CNT_RX_PAUSE    (MAC_OFFSET+ 0x72)
#define ADDR_MAC_TRANS2_PHY_CNT_RX_CRC_ERR  (MAC_OFFSET+ 0x73)
#define ADDR_MAC_TRANS2_PHY_CNT_RX_DROP     (MAC_OFFSET+ 0x74)
#define ADDR_MAC_TRANS2_PHY_CNT_RX_HDR_ERR  (MAC_OFFSET+ 0x75)
#define ADDR_MAC_TRANS2_PHY_CNT_TX_PACK     (MAC_OFFSET+ 0x76)
#define ADDR_MAC_TRANS2_PHY_CNT_TX_PAUSE    (MAC_OFFSET+ 0x77)
#define ADDR_MAC_TRANS2_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0x78)
#define ADDR_MAC_TRANS2_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0x79)
#define ADDR_MAC_TRANS2_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0x7a)
#define ADDR_MAC_TRANS2_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0x7b)
#define ADDR_MAC_TRANS2_BUF_CNT_WR_UNLEGAL  (MAC_OFFSET+ 0x7c)
															 
#define ADDR_MAC_TRANS3_PHY_CNT_RX_UNKNOW   (MAC_OFFSET+ 0x80)
#define ADDR_MAC_TRANS3_PHY_CNT_RX_PACK     (MAC_OFFSET+ 0x81)
#define ADDR_MAC_TRANS3_PHY_CNT_RX_PAUSE    (MAC_OFFSET+ 0x82)
#define ADDR_MAC_TRANS3_PHY_CNT_RX_CRC_ERR  (MAC_OFFSET+ 0x83)
#define ADDR_MAC_TRANS3_PHY_CNT_RX_DROP     (MAC_OFFSET+ 0x84)
#define ADDR_MAC_TRANS3_PHY_CNT_RX_HDR_ERR  (MAC_OFFSET+ 0x85)
#define ADDR_MAC_TRANS3_PHY_CNT_TX_PACK     (MAC_OFFSET+ 0x86)
#define ADDR_MAC_TRANS3_PHY_CNT_TX_PAUSE    (MAC_OFFSET+ 0x87)
#define ADDR_MAC_TRANS3_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0x88)
#define ADDR_MAC_TRANS3_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0x89)
#define ADDR_MAC_TRANS3_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0x8a)
#define ADDR_MAC_TRANS3_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0x8b)
#define ADDR_MAC_TRANS3_BUF_CNT_WR_UNLEGAL  (MAC_OFFSET+ 0x8c)
															 
#define ADDR_MAC_TXBUF0_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0x90)
#define ADDR_MAC_TXBUF0_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0x91)
#define ADDR_MAC_TXBUF0_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0x92)
#define ADDR_MAC_TXBUF0_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0x93)
#define ADDR_MAC_TXBUF1_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0x98)
#define ADDR_MAC_TXBUF1_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0x99)
#define ADDR_MAC_TXBUF1_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0x9a)
#define ADDR_MAC_TXBUF1_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0x9b)
															 
#define ADDR_MAC_TXBUF2_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0xa0)
#define ADDR_MAC_TXBUF2_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0xa1)
#define ADDR_MAC_TXBUF2_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0xa2)
#define ADDR_MAC_TXBUF2_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0xa3)
#define ADDR_MAC_TXBUF3_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0xa8)
#define ADDR_MAC_TXBUF3_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0xa9)
#define ADDR_MAC_TXBUF3_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0xaa)
#define ADDR_MAC_TXBUF3_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0xab)
															 
#define ADDR_MAC_TXBUF4_BUF_CNT_WR_PACK     (MAC_OFFSET+ 0xb0)
#define ADDR_MAC_TXBUF4_BUF_CNT_WR_DROP     (MAC_OFFSET+ 0xb1)
#define ADDR_MAC_TXBUF4_BUF_CNT_RD_PACK     (MAC_OFFSET+ 0xb2)
#define ADDR_MAC_TXBUF4_BUF_CNT_RD_ERR      (MAC_OFFSET+ 0xb3)
															 
#define ADDR_MAC_POOL_DAT_CNT_WR_PACK       (MAC_OFFSET+ 0xc0)
#define ADDR_MAC_POOL_DAT_CNT_WR_DROP       (MAC_OFFSET+ 0xc1)
#define ADDR_MAC_POOL_DAT_CNT_RD_PACK       (MAC_OFFSET+ 0xc2)
#define ADDR_MAC_POOL_DAT_CNT_RD_ERR        (MAC_OFFSET+ 0xc3)
#define ADDR_MAC_POOL_CMD_CNT_WR_PACK       (MAC_OFFSET+ 0xc8)
#define ADDR_MAC_POOL_CMD_CNT_WR_DROP       (MAC_OFFSET+ 0xc9)
#define ADDR_MAC_POOL_CMD_CNT_RD_PACK       (MAC_OFFSET+ 0xca)
#define ADDR_MAC_POOL_CMD_CNT_RD_ERR        (MAC_OFFSET+ 0xcb)
															 
#define ADDR_MAC_RX_ARB_CNT_RX_DAT          (MAC_OFFSET+ 0xd0)
#define ADDR_MAC_RX_ARB_CNT_RX_CMD          (MAC_OFFSET+ 0xd1)
#define ADDR_MAC_RX_ARB_CNT_RX_UNKNOW       (MAC_OFFSET+ 0xd2)



//PCIE卡设备PCIe部分的配置寄存器
//PCIe部分总控
#define  ADDR_PCIE_DMA_CTRL 0x400  //ADDR_DMA_CTRL
#define  ADDR_PCIE_DMA_RST 0x401  //ADDR_MAC_RX_RST
#define  ADDR_PCIE_IP_STATUS0 0x404  //ADDR_PCIE_CFG_COMMAND
#define  ADDR_PCIE_IP_STATUS1 0x405  //ADDR_PCIE_CFG_DSTATUS
#define  ADDR_PCIE_IP_STATUS2 0x406  //ADDR_PCIE_CFG_DCOMMAND
#define  ADDR_PCIE_IP_STATUS3 0x407  //ADDR_PCIE_CFG_LSTATUS
#define  ADDR_PCIE_IP_STATUS4 0x408  //ADDR_PCIE_CFG_LCOMMAND

//CH0
#define  ADDR_PCIE_CH0_TSTREAM_EN 0x500  //ADDR_STREAM_SEL
    #define PCIE_TSTREAM_ENABLE  (1<<0)
    #define PCIE_TSTREAM_DISABLE (0<<0)
#define  ADDR_PCIE_CH0_TSTREAM_NUM 0x501  //ADDR_IMG_NUM
#define  ADDR_PCIE_CH0_TSTREAM_H_SIZE 0x502  //ADDR_IMG_H_SIZE
#define  ADDR_PCIE_CH0_TSTREAM_V_SIZE 0x503  //ADDR_IMG_V_SIZE
#define  ADDR_PCIE_CH0_TSTREAM_HB_SIZE 0x504  //ADDR_IMG_H_BLANK_SIZE
#define  ADDR_PCIE_CH0_TSTREAM_VB_SIZE 0x505  //ADDR_IMG_V_BLANK_SIZE

#define  ADDR_PCIE_DMA_CH0_CTRL 0x507
    #define PCIE_CH_DMA_ENABLE (1<<0)
    #define PCIE_CH_DMA_RESET  (1<<1)
#define  ADDR_PCIE_DMA_CH0_BDMEM_ADDR 0x508  //ADDR_DMA_BDMEM_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_WDATA0 0x509  //ADDR_DMA_BDMEM_WDATA0
#define  ADDR_PCIE_DMA_CH0_BDMEM_WDATA1 0x50A  //ADDR_DMA_BDMEM_WDATA1
#define  ADDR_PCIE_DMA_CH0_BDMEM_WDATA2 0x50B  //ADDR_DMA_BDMEM_WDATA2
#define  ADDR_PCIE_DMA_CH0_BDMEM_RDATA0 0x50C  //ADDR_DMA_BDMEM_RDATA0
#define  ADDR_PCIE_DMA_CH0_BDMEM_RDATA1 0x50D  //ADDR_DMA_BDMEM_RDATA1
#define  ADDR_PCIE_DMA_CH0_BDMEM_RDATA2 0x50E  //ADDR_DMA_BDMEM_RDATA2
#define  ADDR_PCIE_DMA_CH0_BDMEM_BKNUM 0x50F  //ADDR_DMA_BDMEM_BKNUM
#define  ADDR_PCIE_DMA_CH0_BDMEM_LATEST_ID 0x510  //ADDR_DMA_BDMEM_LATEST_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_VALID 0x511  //ADDR_DMA_BDMEM_VALID
#define  ADDR_PCIE_DMA_CH0_BDMEM_VALID_CLR 0x512  //ADDR_DMA_BDMEM_BK_CLR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BUSY	  0x513
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK0_ADDR 0x514  //ADDR_DMA_BDMEM_BK0_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK0_CTRL 0x515  //ADDR_DMA_BDMEM_BK0_CTRL
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK0_ID 0x516  //ADDR_DMA_BDMEM_BK0_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK0_SIZE 0x517  //ADDR_DMA_BDMEM_BK0_SIZE
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK0_XOR  0x518

#define  ADDR_PCIE_DMA_CH0_BDMEM_BK1_ADDR 0x51C  //ADDR_DMA_BDMEM_BK1_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK1_CTRL 0x51D  //ADDR_DMA_BDMEM_BK1_CTRL
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK1_ID 0x51E  //ADDR_DMA_BDMEM_BK1_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK1_SIZE 0x51F  //ADDR_DMA_BDMEM_BK1_SIZE

#define  ADDR_PCIE_DMA_CH0_BDMEM_BK2_ADDR 0x524  //ADDR_DMA_BDMEM_BK2_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK2_CTRL 0x525  //ADDR_DMA_BDMEM_BK2_CTRL
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK2_ID 0x526  //ADDR_DMA_BDMEM_BK2_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK2_SIZE 0x527  //ADDR_DMA_BDMEM_BK2_SIZE

#define  ADDR_PCIE_DMA_CH0_BDMEM_BK3_ADDR 0x52C  //ADDR_DMA_BDMEM_BK3_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK3_CTRL 0x52D  //ADDR_DMA_BDMEM_BK3_CTRL
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK3_ID 0x52E  //ADDR_DMA_BDMEM_BK3_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK3_SIZE 0x52F  //ADDR_DMA_BDMEM_BK3_SIZE

#define  ADDR_PCIE_DMA_CH0_BDMEM_BK4_ADDR 0x534  //ADDR_DMA_BDMEM_BK4_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK4_CTRL 0x535  //ADDR_DMA_BDMEM_BK4_CTRL
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK4_ID 0x536  //ADDR_DMA_BDMEM_BK4_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK4_SIZE 0x537  //ADDR_DMA_BDMEM_BK4_SIZE

#define  ADDR_PCIE_DMA_CH0_BDMEM_BK5_ADDR 0x53C  //ADDR_DMA_BDMEM_BK5_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK5_CTRL 0x53D  //ADDR_DMA_BDMEM_BK5_CTRL
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK5_ID 0x53E  //ADDR_DMA_BDMEM_BK5_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK5_SIZE 0x53F  //ADDR_DMA_BDMEM_BK5_SIZE

#define  ADDR_PCIE_DMA_CH0_BDMEM_BK6_ADDR 0x544  //ADDR_DMA_BDMEM_BK6_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK6_CTRL 0x545  //ADDR_DMA_BDMEM_BK6_CTRL
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK6_ID 0x546  //ADDR_DMA_BDMEM_BK6_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK6_SIZE 0x547  //ADDR_DMA_BDMEM_BK6_SIZE

#define  ADDR_PCIE_DMA_CH0_BDMEM_BK7_ADDR 0x54C  //ADDR_DMA_BDMEM_BK7_ADDR
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK7_CTRL 0x54D  //ADDR_DMA_BDMEM_BK7_CTRL
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK7_ID 0x54E  //ADDR_DMA_BDMEM_BK7_ID
#define  ADDR_PCIE_DMA_CH0_BDMEM_BK7_SIZE 0x54F  //ADDR_DMA_BDMEM_BK7_SIZE

#define	 ADDR_PCIE_DMA_CH0_MATCH_ETH_ADDR_H	0x594  // 接收数据流的以太网ETH地址
#define	 ADDR_PCIE_DMA_CH0_MATCH_ETH_ADDR_L	0x595  // 接收数据流的以太网ETH地址
#define  ADDR_PCIE_DMA_CH0_MATCH_IP_ADDR    0x596  // 接收数据流的IP地址
#define  ADDR_PCIE_DMA_CH0_MATCH_UDP_PORT	0x597  // 接收数据流的UDP端口


#define  ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_SIZE 0x5F8  //新增
#define  ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_CNT 0x5F9  //新增
#define  ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_TOTALSIZE 0x5FA  //新增
#define  ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_LOSTSIZE 0x5FB  //新增
#define  ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_SIZE 0x5FC  //新增
#define  ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_CNT 0x5FD  //新增
#define  ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_TOTALSIZE 0x5FE  //新增
#define  ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_SIZECHANGE_CNT 0x5FF  //新增

//CH1
#define  ADDR_PCIE_CH1_TSTREAM_EN ( ADDR_PCIE_CH0_TSTREAM_EN + 0x100)
#define  ADDR_PCIE_CH1_TSTREAM_NUM ( ADDR_PCIE_CH0_TSTREAM_NUM + 0x100)
#define  ADDR_PCIE_CH1_TSTREAM_H_SIZE ( ADDR_PCIE_CH0_TSTREAM_H_SIZE + 0x100)
#define  ADDR_PCIE_CH1_TSTREAM_V_SIZE ( ADDR_PCIE_CH0_TSTREAM_V_SIZE + 0x100)
#define  ADDR_PCIE_CH1_TSTREAM_HB_SIZE ( ADDR_PCIE_CH0_TSTREAM_HB_SIZE + 0x100)
#define  ADDR_PCIE_CH1_TSTREAM_VB_SIZE ( ADDR_PCIE_CH0_TSTREAM_VB_SIZE + 0x100)

#define  ADDR_PCIE_DMA_CH1_CTRL ( ADDR_PCIE_DMA_CH0_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_WDATA0 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA0 + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_WDATA1 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA1 + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_WDATA2 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA2 + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_RDATA0 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA0 + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_RDATA1 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA1 + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_RDATA2 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA2 + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BKNUM ( ADDR_PCIE_DMA_CH0_BDMEM_BKNUM + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_LATEST_ID ( ADDR_PCIE_DMA_CH0_BDMEM_LATEST_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_VALID ( ADDR_PCIE_DMA_CH0_BDMEM_VALID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_VALID_CLR ( ADDR_PCIE_DMA_CH0_BDMEM_VALID_CLR + 0x100)

#define  ADDR_PCIE_DMA_CH1_BDMEM_BK0_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK0_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK0_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK0_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_SIZE + 0x100)

#define  ADDR_PCIE_DMA_CH1_BDMEM_BK1_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK1_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK1_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK1_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_SIZE + 0x100)

#define  ADDR_PCIE_DMA_CH1_BDMEM_BK2_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK2_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK2_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK2_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_SIZE + 0x100)

#define  ADDR_PCIE_DMA_CH1_BDMEM_BK3_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK3_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK3_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK3_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_SIZE + 0x100)

#define  ADDR_PCIE_DMA_CH1_BDMEM_BK4_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK4_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK4_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK4_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_SIZE + 0x100)

#define  ADDR_PCIE_DMA_CH1_BDMEM_BK5_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK5_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK5_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK5_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_SIZE + 0x100)

#define  ADDR_PCIE_DMA_CH1_BDMEM_BK6_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK6_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK6_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK6_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_SIZE + 0x100)

#define  ADDR_PCIE_DMA_CH1_BDMEM_BK7_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_ADDR + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK7_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_CTRL + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK7_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_ID + 0x100)
#define  ADDR_PCIE_DMA_CH1_BDMEM_BK7_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_SIZE + 0x100)

#define  ADDR_DEBUG_PCIE_DMA_CH1_STREAM_IN_SIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_SIZE + 0x100)
#define  ADDR_DEBUG_PCIE_DMA_CH1_STREAM_IN_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_CNT + 0x100)
#define  ADDR_DEBUG_PCIE_DMA_CH1_STREAM_IN_TOTALSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_TOTALSIZE + 0x100)
#define  ADDR_DEBUG_PCIE_DMA_CH1_STREAM_IN_LOSTSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_LOSTSIZE + 0x100)
#define  ADDR_DEBUG_PCIE_DMA_CH1_STREAM_OUT_SIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_SIZE + 0x100)
#define  ADDR_DEBUG_PCIE_DMA_CH1_STREAM_OUT_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_CNT + 0x100)
#define  ADDR_DEBUG_PCIE_DMA_CH1_STREAM_OUT_TOTALSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_TOTALSIZE + 0x100)
#define  ADDR_DEBUG_PCIE_DMA_CH1_STREAM_OUT_SIZECHANGE_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_SIZECHANGE_CNT + 0x100)

//CH2
#define  ADDR_PCIE_CH2_TSTREAM_EN ( ADDR_PCIE_CH0_TSTREAM_EN + 0x200)
#define  ADDR_PCIE_CH2_TSTREAM_NUM ( ADDR_PCIE_CH0_TSTREAM_NUM + 0x200)
#define  ADDR_PCIE_CH2_TSTREAM_H_SIZE ( ADDR_PCIE_CH0_TSTREAM_H_SIZE + 0x200)
#define  ADDR_PCIE_CH2_TSTREAM_V_SIZE ( ADDR_PCIE_CH0_TSTREAM_V_SIZE + 0x200)
#define  ADDR_PCIE_CH2_TSTREAM_HB_SIZE ( ADDR_PCIE_CH0_TSTREAM_HB_SIZE + 0x200)
#define  ADDR_PCIE_CH2_TSTREAM_VB_SIZE ( ADDR_PCIE_CH0_TSTREAM_VB_SIZE + 0x200)

#define  ADDR_PCIE_DMA_CH2_CTRL ( ADDR_PCIE_DMA_CH0_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_WDATA0 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA0 + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_WDATA1 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA1 + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_WDATA2 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA2 + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_RDATA0 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA0 + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_RDATA1 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA1 + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_RDATA2 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA2 + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BKNUM ( ADDR_PCIE_DMA_CH0_BDMEM_BKNUM + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_LATEST_ID ( ADDR_PCIE_DMA_CH0_BDMEM_LATEST_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_VALID ( ADDR_PCIE_DMA_CH0_BDMEM_VALID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_VALID_CLR ( ADDR_PCIE_DMA_CH0_BDMEM_VALID_CLR + 0x200)

#define  ADDR_PCIE_DMA_CH2_BDMEM_BK0_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK0_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK0_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK0_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_SIZE + 0x200)

#define  ADDR_PCIE_DMA_CH2_BDMEM_BK1_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK1_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK1_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK1_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_SIZE + 0x200)

#define  ADDR_PCIE_DMA_CH2_BDMEM_BK2_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK2_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK2_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK2_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_SIZE + 0x200)

#define  ADDR_PCIE_DMA_CH2_BDMEM_BK3_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK3_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK3_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK3_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_SIZE + 0x200)

#define  ADDR_PCIE_DMA_CH2_BDMEM_BK4_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK4_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK4_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK4_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_SIZE + 0x200)

#define  ADDR_PCIE_DMA_CH2_BDMEM_BK5_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK5_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK5_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK5_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_SIZE + 0x200)

#define  ADDR_PCIE_DMA_CH2_BDMEM_BK6_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK6_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK6_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK6_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_SIZE + 0x200)

#define  ADDR_PCIE_DMA_CH2_BDMEM_BK7_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_ADDR + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK7_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_CTRL + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK7_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_ID + 0x200)
#define  ADDR_PCIE_DMA_CH2_BDMEM_BK7_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_SIZE + 0x200)

#define  ADDR_DEBUG_PCIE_DMA_CH2_STREAM_IN_SIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_SIZE + 0x200)
#define  ADDR_DEBUG_PCIE_DMA_CH2_STREAM_IN_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_CNT + 0x200)
#define  ADDR_DEBUG_PCIE_DMA_CH2_STREAM_IN_TOTALSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_TOTALSIZE + 0x200)
#define  ADDR_DEBUG_PCIE_DMA_CH2_STREAM_IN_LOSTSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_LOSTSIZE + 0x200)
#define  ADDR_DEBUG_PCIE_DMA_CH2_STREAM_OUT_SIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_SIZE + 0x200)
#define  ADDR_DEBUG_PCIE_DMA_CH2_STREAM_OUT_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_CNT + 0x200)
#define  ADDR_DEBUG_PCIE_DMA_CH2_STREAM_OUT_TOTALSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_TOTALSIZE + 0x200)
#define  ADDR_DEBUG_PCIE_DMA_CH2_STREAM_OUT_SIZECHANGE_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_SIZECHANGE_CNT + 0x200)

//CH3
#define  ADDR_PCIE_CH3_TSTREAM_EN ( ADDR_PCIE_CH0_TSTREAM_EN + 0x300)
#define  ADDR_PCIE_CH3_TSTREAM_NUM ( ADDR_PCIE_CH0_TSTREAM_NUM + 0x300)
#define  ADDR_PCIE_CH3_TSTREAM_H_SIZE ( ADDR_PCIE_CH0_TSTREAM_H_SIZE + 0x300)
#define  ADDR_PCIE_CH3_TSTREAM_V_SIZE ( ADDR_PCIE_CH0_TSTREAM_V_SIZE + 0x300)
#define  ADDR_PCIE_CH3_TSTREAM_HB_SIZE ( ADDR_PCIE_CH0_TSTREAM_HB_SIZE + 0x300)
#define  ADDR_PCIE_CH3_TSTREAM_VB_SIZE ( ADDR_PCIE_CH0_TSTREAM_VB_SIZE + 0x300)

#define  ADDR_PCIE_DMA_CH3_CTRL ( ADDR_PCIE_DMA_CH0_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_WDATA0 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA0 + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_WDATA1 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA1 + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_WDATA2 ( ADDR_PCIE_DMA_CH0_BDMEM_WDATA2 + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_RDATA0 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA0 + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_RDATA1 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA1 + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_RDATA2 ( ADDR_PCIE_DMA_CH0_BDMEM_RDATA2 + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BKNUM ( ADDR_PCIE_DMA_CH0_BDMEM_BKNUM + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_LATEST_ID ( ADDR_PCIE_DMA_CH0_BDMEM_LATEST_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_VALID ( ADDR_PCIE_DMA_CH0_BDMEM_VALID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_VALID_CLR ( ADDR_PCIE_DMA_CH0_BDMEM_VALID_CLR + 0x300)

#define  ADDR_PCIE_DMA_CH3_BDMEM_BK0_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK0_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK0_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK0_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK0_SIZE + 0x300)

#define  ADDR_PCIE_DMA_CH3_BDMEM_BK1_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK1_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK1_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK1_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK1_SIZE + 0x300)

#define  ADDR_PCIE_DMA_CH3_BDMEM_BK2_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK2_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK2_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK2_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK2_SIZE + 0x300)

#define  ADDR_PCIE_DMA_CH3_BDMEM_BK3_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK3_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK3_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK3_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK3_SIZE + 0x300)

#define  ADDR_PCIE_DMA_CH3_BDMEM_BK4_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK4_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK4_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK4_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK4_SIZE + 0x300)

#define  ADDR_PCIE_DMA_CH3_BDMEM_BK5_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK5_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK5_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK5_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK5_SIZE + 0x300)

#define  ADDR_PCIE_DMA_CH3_BDMEM_BK6_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK6_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK6_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK6_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK6_SIZE + 0x300)

#define  ADDR_PCIE_DMA_CH3_BDMEM_BK7_ADDR ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_ADDR + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK7_CTRL ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_CTRL + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK7_ID ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_ID + 0x300)
#define  ADDR_PCIE_DMA_CH3_BDMEM_BK7_SIZE ( ADDR_PCIE_DMA_CH0_BDMEM_BK7_SIZE + 0x300)

#define  ADDR_DEBUG_PCIE_DMA_CH3_STREAM_IN_SIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_SIZE + 0x300)
#define  ADDR_DEBUG_PCIE_DMA_CH3_STREAM_IN_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_CNT + 0x300)
#define  ADDR_DEBUG_PCIE_DMA_CH3_STREAM_IN_TOTALSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_TOTALSIZE + 0x300)
#define  ADDR_DEBUG_PCIE_DMA_CH3_STREAM_IN_LOSTSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_IN_LOSTSIZE + 0x300)
#define  ADDR_DEBUG_PCIE_DMA_CH3_STREAM_OUT_SIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_SIZE + 0x300)
#define  ADDR_DEBUG_PCIE_DMA_CH3_STREAM_OUT_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_CNT + 0x300)
#define  ADDR_DEBUG_PCIE_DMA_CH3_STREAM_OUT_TOTALSIZE ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_TOTALSIZE + 0x300)
#define  ADDR_DEBUG_PCIE_DMA_CH3_STREAM_OUT_SIZECHANGE_CNT ( ADDR_DEBUG_PCIE_DMA_CH0_STREAM_OUT_SIZECHANGE_CNT + 0x300)

